FROM ghcr.io/nerfstudio-project/nerfstudio:latest
ENV DEBIAN_FRONTEND=noninteractive

COPY hello.sh /

ENV PIP_ROOT_USER_ACTION=ignore

## Installing rosdep https://wiki.ros.org/rosdep
#RUN sudo apt update &&\
#    pip install -U rosdep &&\
#    rosdep init && \ 
#    rosdep update && \
## Installing catkin (maybe)
#    apt install catkin -y

RUN apt-get update &&\
    apt install ros-desktop-full -y

# Step 3 (incomplete)
# RUN apt update &&\
#    apt install -y \
#    python3-rosdep \
#    python3-rosinstall-generator \
#    python3-vcstool \
#    build-essential \
#    git &&\
#    sudo rosdep init &&\
#    rosdep update



RUN chmod +x /hello.sh

#CMD ["catkin", "build nerf_teleoperation"]
#CMD ["source", "devel/setup.bash"]
CMD ["/hello.sh"]