FROM ghcr.io/nerfstudio-project/nerfstudio:main
ENV DEBIAN_FRONTEND=noninteractive

COPY hello.sh /

ENV PIP_ROOT_USER_ACTION=ignore

## 1. Installing ROS1

RUN apt-get update &&\
    apt install ros-desktop-full -y

## 1.2Install Catkin (not sure whether nec)
#RUN git clone https://github.com/catkin/catkin_tools.git
#WORKDIR catkin_tools
#RUN pip3 install -r requirements.txt --upgrade &&\
#    python3 setup.py install --record install_manifest.txt&&\
#    python3 setup.py develop


# 2. Install pipeline-project
RUN mkdir -p /workspace/src
WORKDIR /workspace/src
RUN git clone https://github.com/leggedrobotics/radiance_field_ros.git .
WORKDIR /workspace
# catkin build nerf_teleoperation + "source the workspace"

RUN chmod +x /hello.sh

CMD ["/hello.sh"]